version: '3.8'

# 开发环境配置 - 只启动Redis，其他服务由本地manager管理
services:
  # Redis 消息总线
  redis:
    image: redis:7-alpine
    container_name: aivtuber-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped

volumes:
  redis_dev_data:

networks:
  default:
    name: aivtuber-dev-network